#!/usr/bin/env bash
# 🍎 KIRA INSTALLER — Production Automated Preseed
# "I'll take a potato chip... and AUTOMATE IT."

INSTALL_MODE="single"
SELECTED_DISK="/dev/sda"
HOSTNAME="kira-production"
USERNAME="light"

ENCRYPTION="luks2+lvm"
SWAP_SIZE="4G"
ROOT_SIZE="40G"

# AUTO=true
# NO_BANNER=true
# NO_CONFIRM=true
